<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Insert title here</title>
    <script src="/resources/jquery/jquery.min_1_12.js"></script>
    <script src="/resources/jquery/jquery.fixedheadertable.min.js"></script>
    <script>
        //$('#headerFixTable').fixheadertable({height: '200',minWidth:800,caption:'my header is fixed', zebra : true});
        $(document).ready(function () {
            $('#fixed_table').fixedHeaderTable({
                footer: false,
                cloneHeadToFoot: true,
            });


            //$('#fixed_table').fixedHeaderTable({height: '200', minWidth:200, caption:'my header is fixed', zebra : true});
        });
    </script>
</head>
<body>
    <div style="width: 500px;">
        <table id="fixed_table" border="1" width="500">
            <thead>
                <tr>
                    <th>열이름1</th>
                    <th>열이름2</th>
                    <th>열이름3</th>
                    <th>열이름4</th>
                    <th>열이름5</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
                <tr>
                    <td>테스트1</td>
                    <td>테스트2</td>
                    <td>테스트3</td>
                    <td>테스트4</td>
                    <td>테스트5</td>
                </tr>
            </tbody>
        </table>
    </div>
    <%
        //============================================================
        //  에러 메시지 처리
        //============================================================
        if(session.getAttribute("sERRORMSG") != null){
            out.println("<script type=\"text/javascript\">alert('"+session.getAttribute("sERRORMSG")+"');</script>");
            session.removeAttribute("sERRORMSG");
        }
    %>
</body>
</html>